# Generated by Django 5.1.1 on 2024-10-05 18:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Image_Effects_handler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='UserImages',
        ),
    ]
