# Generated by Django 5.1.1 on 2024-10-05 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Image_Effects_handler', '0002_rename_image_userimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userimages',
            old_name='Image',
            new_name='image',
        ),
    ]
