# Generated by Django 5.1.1 on 2024-10-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image_Effects_handler', '0002_alter_userimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimages',
            name='public_id',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
