# Generated by Django 5.1.1 on 2024-10-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image_Effects_handler', '0005_alter_userimages_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimages',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
